CC      = gcc
CFLAGS  = -Wall -g -D_POSIX_SOURCE -D_DEFAULT_SOURCE -std=c99 -Werror -pedantic

.SUFFIXES: .c .o

.PHONY: all clean

all: assemble emulate

assemble: assemble.o

emulate: emulate.o

assemble.o: /assemble_utils/defs.h /assemble_utils/utils.h /assemble_utils/instruction_assembler.h

clean:
	rm -f $(wildcard *.o)
	rm -f assemble
	rm -f emulate
